#!/bin/bash -e

CONFIG=$1
LIBS="${HOME}/bin/riemann-0.2.6/lib"
RIEMANN_JAR="${LIBS}/riemann.jar"
LENGOHR_JAR="${LIBS}/lengohr.jar"
MAIN_CLASS="riemann.bin"
OPTS="-XX:+UseConcMarkSweepGC \
      -XX:+UseParNewGC \
      -XX:+CMSParallelRemarkEnabled \
      -XX:+AggressiveOpts \
      -XX:+UseFastAccessorMethods \
      -XX:+UseCompressedOops \
      -XX:+CMSClassUnloadingEnabled"

exec java ${OPTS} -cp "${RIEMANN_JAR}:${LENGOHR_JAR}" ${MAIN_CLASS} ${CONFIG}
