#!/bin/bash -e

CONFIG=$1
RIEMANN_HOME="$(dirname $(which riemann))/.."
RIEMANN_JAR="${RIEMANN_HOME}/lib/riemann.jar"
LENGOHR_JAR="${LENGOHR_JAR=${RIEMANN_HOME}/lib/lengohr.jar}"
MAIN_CLASS="riemann.bin"
OPTS="-XX:+UseConcMarkSweepGC \
      -XX:+UseParNewGC \
      -XX:+CMSParallelRemarkEnabled \
      -XX:+AggressiveOpts \
      -XX:+UseFastAccessorMethods \
      -XX:+UseCompressedOops \
      -XX:+CMSClassUnloadingEnabled"

exec java ${OPTS} -cp "${RIEMANN_JAR}:${LENGOHR_JAR}" ${MAIN_CLASS} ${CONFIG}
