version: "3.8"

services:
#  mgmtworker:
#    container_name: mgmtworker
#    build: mgmtworker
#    env_file:
#      - .env
#    volumes:
#      - ../cloudify_internal_ca_cert.pem:/opt/mgmtworker/cloudify_internal_ca_cert.pem
#      - ./resources/rest-service/cloudify/types:/opt/manager/resources/cloudify/types
#    networks:
#      - cloudify
#    restart: unless-stopped

  rest_service:
    container_name: rest_service
    build: rest-service
    depends_on:
      - postgresql
    networks:
      - cloudify
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_DB: cloudify_db
      POSTGRES_USER: cloudify
      POSTGRES_PASSWORD: cloudify
    volumes:
      - ./packaging/db-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - cloudify
    restart: unless-stopped

networks:
  cloudify:
    driver: bridge
    name: cloudify
