version: "3.8"

services:
  # mgmtworker is disabled until nginx is present - cannot call the API just yet
  # mgmtworker:
  #   container_name: mgmtworker
  #   build:
  #     dockerfile: mgmtworker/Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - cloudify
  #   restart: unless-stopped

  rest_service:
    container_name: rest_service
    build: rest-service
    env_file:
      - .env
    networks:
      - cloudify
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres
    env_file:
      - .env
    volumes:
      - ../db-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - cloudify
    restart: unless-stopped

networks:
  cloudify:
    driver: bridge
    name: cloudify
