pipeline {
    agent {
        node 'docker'
    }
    parameters {
        string(name: 'BRANCH', defaultValue: 'master')
        string(name: 'IMAGE_BUILD_NUMBER')
        booleanParam(name: 'FETCH_IMAGE', defaultValue: false)
        text(name: 'PYTEST_ARGS', defaultValue: """-sv \\
tests/integration_tests/tests/agentless_tests/test_workflow.py \\
tests/integration_tests/tests/agentless_tests/test_resume.py \\
tests/integration_tests/tests/agentless_tests/test_rest_api.py \\
tests/integration_tests/tests/agentless_tests/test_rest_service_list_filters.py \\
tests/integration_tests/tests/agentless_tests/test_rest_service_pagination.py \\
tests/integration_tests/tests/agentless_tests/test_rest_service_sort.py \\
tests/integration_tests/tests/agentless_tests/test_n_instances.py \\
tests/integration_tests/tests/agentless_tests/test_deployment_creation.py \\
tests/integration_tests/tests/agentless_tests/test_deployment_logs.py \\
tests/integration_tests/tests/agentless_tests/test_deployment_nodes.py \\
tests/integration_tests/tests/agentless_tests/test_deployment_resource.py \\
tests/integration_tests/tests/agentless_tests/test_deployment_workflows.py \\
tests/integration_tests/tests/agentless_tests/test_uninstall_deployment.py \\
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_addition.py \\
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_misc.py \\
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_mixed_operations.py \\
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_modification.py \\
tests/integration_tests/tests/agentless_tests/deployment_update/test_deployment_update_removal.py \\
tests/integration_tests/tests/agentless_tests/component/test_component_auto_inc_suffix.py \\
tests/integration_tests/tests/agentless_tests/component/test_component_basics.py \\
tests/integration_tests/tests/agentless_tests/component/test_component_cascading.py \\
tests/integration_tests/tests/agentless_tests/shared_resource/test_relationship_running_workflow.py \\
tests/integration_tests/tests/agentless_tests/shared_resource/test_shared_resource_type.py \\
tests/integration_tests/tests/agent_tests/test_agent_install_from_plugin.py \\
tests/integration_tests/tests/agent_tests/test_agent_install_workflow.py""")
    }
    stages {
        stage('Fetch the docker image'){
            when {
                expression { return params.FETCH_IMAGE }
            }
            steps {
                sh '''
                    docker rmi -f cloudify-manager-aio:latest
                '''
                copyArtifacts(
                    projectName: '/dir_manager/build_docker_image_pipeline',
                    selector: params.IMAGE_BUILD_NUMBER ? specific(params.IMAGE_BUILD_NUMBER) : lastSuccessful()
                )
                sh '''
                    docker load -i cloudify*.tar
                '''
            }
        }
        stage('install the inte-tests package') {
            steps {
                sh '''
                    virtualenv venv
                    venv/bin/pip install 'https://github.com/cloudify-cosmo/cloudify-common/archive/master.zip#egg=cloudify-common[dispatcher]'
                    venv/bin/pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/master.zip
                    venv/bin/pip install rest-service/
                    venv/bin/pip install tests/
                '''
            }
        }
        stage('run tests'){
            steps {
                sh """
                    export CI=no-color-logs
                    source venv/bin/activate
                    venv/bin/pytest \
                        ${params.PYTEST_ARGS} \
                        --junitxml=test-results.xml
                """
            }
            post {
                always {
                    junit 'test-results.xml'
                }
                cleanup {

                    cleanWs()
                }
            }
        }
    }
}