__author__ = 'elip'

COSMO_VERSION = "master"

FABRIC_RUNNER_VERSION = "master"
WORKER_INSTALLER_VERSION = "master"
RIEMANN_LOADER_VERSION = "master"
VAGRANT_PROVISION_VERSION = "master"
OPENSTACK_PROVISION_VERSION = "master"
DSL_PARSER_VERSION = "master"
