__author__ = 'elip'

COSMO_VERSION = '0.2'

FABRIC_RUNNER_VERSION = '0.2'
WORKER_INSTALLER_VERSION = '0.2'
RIEMANN_LOADER_VERSION = '0.2'
VAGRANT_PROVISION_VERSION = '0.2'
OPENSTACK_PROVISION_VERSION = '0.2'
DSL_PARSER_VERSION = '0.2'
