__author__ = 'elip'

FABRIC_RUNNER_VERSION = "develop"
WORKER_INSTALLER_VERSION = "develop"
RIEMANN_LOADER_VERSION = "develop"
VAGRANT_PROVISION_VERSION = "0.1.0"
OPENSTACK_PROVISION_VERSION = "develop"
DSL_PARSER_VERSION = "develop"
