"""4.2 to 4.3 - add groups_roles relation

Revision ID: 784a82cec07a
Revises: f1dab814a4a0
Create Date: 2017-11-19 11:38:04.633560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784a82cec07a'
down_revision = 'f1dab814a4a0'
branch_labels = None
depends_on = None

DEFAULT_SYSTEM_ROLE_ID = 6


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'groups_roles',
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], )
    )
    op.execute(
        'INSERT INTO groups_roles '
        'SELECT id, {0} '
        'FROM groups'.format(DEFAULT_SYSTEM_ROLE_ID)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_roles')
    # ### end Alembic commands ###
