#########
# Copyright (c) 2013 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#

source 'https://rubygems.org'

gem 'unicorn', '~> 4.8.2'
gem 'rufus-scheduler', '~> 2.0.24'
gem 'sinatra', '~> 1.4.4'
gem 'ruote', '~> 2.3.0.2'
gem 'rest-client', '~> 1.6.7'
gem 'bunny', '~> 1.1.2'
gem "riemann-client", "~> 0.2.2"

group :test do
  gem 'rack-test', '~> 0.6.2'
  gem 'test-unit', '~> 2.5.5'
end

