"""5.0.5 to 5.1
 - Add usage_collector table

Revision ID: 1df4f837a53b
Revises: 62a8d746d13b
Create Date: 2020-03-26 12:52:58.605625

"""
from alembic import op
import sqlalchemy as sa

from manager_rest.storage.models_base import UTCDateTime

# revision identifiers, used by Alembic.
revision = '1df4f837a53b'
down_revision = '62a8d746d13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_collector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.Text(), nullable=False),
    sa.Column('hourly_timestamp', UTCDateTime(), nullable=True),
    sa.Column('daily_timestamp', UTCDateTime(), nullable=True),
    sa.Column('hours_interval', sa.Integer(), nullable=False),
    sa.Column('days_interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('manager_id', name=op.f('usage_collector_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_collector')
    # ### end Alembic commands ###
