"""empty message

Revision ID: 39d6695f4ee8
Revises: 62a8d746d13b
Create Date: 2019-12-02 10:34:53.430023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d6695f4ee8'
down_revision = '62a8d746d13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'plugins',
        sa.Column('supported_cloudify', sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'supported_cloudify')
    # ### end Alembic commands ###
