""" (4.1) Add RabbitMQ details to tenant model

Revision ID: 730403566523
Revises: 9aa6f74c9653
Create Date: 2017-05-10 15:33:46.837856

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '730403566523'
down_revision = '9aa6f74c9653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('blueprints_created_at_idx'),
        'blueprints',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('blueprints_id_idx'),
        'blueprints',
        ['id'],
        unique=False)
    op.create_index(
        op.f('deployment_modifications_created_at_idx'),
        'deployment_modifications',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('deployment_modifications_ended_at_idx'),
        'deployment_modifications',
        ['ended_at'],
        unique=False)
    op.create_index(
        op.f('deployment_modifications_id_idx'),
        'deployment_modifications',
        ['id'],
        unique=False)
    op.create_index(
        op.f('deployment_update_steps_id_idx'),
        'deployment_update_steps',
        ['id'],
        unique=False)
    op.create_index(
        op.f('deployment_updates_created_at_idx'),
        'deployment_updates',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('deployment_updates_id_idx'),
        'deployment_updates',
        ['id'],
        unique=False)
    op.create_index(
        op.f('deployments_created_at_idx'),
        'deployments',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('deployments_id_idx'),
        'deployments',
        ['id'],
        unique=False)
    op.create_index(
        op.f('events_id_idx'),
        'events',
        ['id'],
        unique=False)
    op.create_index(
        op.f('events_timestamp_idx'),
        'events',
        ['timestamp'],
        unique=False)
    op.drop_index('ix_events_timestamp', table_name='events')
    op.create_index(
        op.f('executions_created_at_idx'),
        'executions',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('executions_id_idx'),
        'executions',
        ['id'],
        unique=False)
    op.create_index(
        op.f('groups_ldap_dn_idx'),
        'groups',
        ['ldap_dn'],
        unique=True)
    op.create_index(
        op.f('groups_name_idx'),
        'groups',
        ['name'],
        unique=True)
    op.create_index(
        op.f('logs_id_idx'),
        'logs',
        ['id'],
        unique=False)
    op.create_index(
        op.f('logs_timestamp_idx'),
        'logs',
        ['timestamp'],
        unique=False)
    op.drop_index('ix_logs_timestamp', table_name='logs')
    op.create_index(
        op.f('node_instances_id_idx'),
        'node_instances',
        ['id'],
        unique=False)
    op.create_index(
        op.f('nodes_id_idx'),
        'nodes',
        ['id'],
        unique=False)
    op.create_index(
        op.f('nodes_type_idx'),
        'nodes',
        ['type'],
        unique=False)
    op.create_index(
        op.f('plugins_archive_name_idx'),
        'plugins',
        ['archive_name'],
        unique=False)
    op.create_index(
        op.f('plugins_id_idx'),
        'plugins',
        ['id'],
        unique=False)
    op.create_index(
        op.f('plugins_package_name_idx'),
        'plugins',
        ['package_name'],
        unique=False)
    op.create_index(
        op.f('plugins_uploaded_at_idx'),
        'plugins',
        ['uploaded_at'],
        unique=False)
    op.create_index(
        op.f('roles_name_idx'),
        'roles',
        ['name'],
        unique=True)
    op.create_index(
        op.f('secrets_created_at_idx'),
        'secrets',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('secrets_id_idx'),
        'secrets',
        ['id'],
        unique=False)
    op.create_index(
        op.f('snapshots_created_at_idx'),
        'snapshots',
        ['created_at'],
        unique=False)
    op.create_index(
        op.f('snapshots_id_idx'),
        'snapshots',
        ['id'],
        unique=False)
    op.add_column(
        'tenants',
        sa.Column('rabbitmq_password',
                  sa.Text(),
                  nullable=True)
    )
    op.add_column(
        'tenants',
        sa.Column('rabbitmq_username',
                  sa.Text(),
                  nullable=True)
    )
    op.add_column(
        'tenants',
        sa.Column('rabbitmq_vhost',
                  sa.Text(),
                  nullable=True)
    )
    op.create_index(op.f('tenants_name_idx'), 'tenants', ['name'], unique=True)
    op.create_index(
        op.f('users_username_idx'),
        'users',
        ['username'],
        unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('tenants_name_idx'), table_name='tenants')
    op.drop_column('tenants', 'rabbitmq_vhost')
    op.drop_column('tenants', 'rabbitmq_username')
    op.drop_column('tenants', 'rabbitmq_password')
    op.drop_index(op.f('snapshots_id_idx'), table_name='snapshots')
    op.drop_index(op.f('snapshots_created_at_idx'), table_name='snapshots')
    op.drop_index(op.f('secrets_id_idx'), table_name='secrets')
    op.drop_index(op.f('secrets_created_at_idx'), table_name='secrets')
    op.drop_index(op.f('roles_name_idx'), table_name='roles')
    op.drop_index(op.f('plugins_uploaded_at_idx'), table_name='plugins')
    op.drop_index(op.f('plugins_package_name_idx'), table_name='plugins')
    op.drop_index(op.f('plugins_id_idx'), table_name='plugins')
    op.drop_index(op.f('plugins_archive_name_idx'), table_name='plugins')
    op.drop_index(op.f('nodes_type_idx'), table_name='nodes')
    op.drop_index(op.f('nodes_id_idx'), table_name='nodes')
    op.drop_index(op.f('node_instances_id_idx'), table_name='node_instances')
    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    op.drop_index(op.f('logs_timestamp_idx'), table_name='logs')
    op.drop_index(op.f('logs_id_idx'), table_name='logs')
    op.drop_index(op.f('groups_name_idx'), table_name='groups')
    op.drop_index(op.f('groups_ldap_dn_idx'), table_name='groups')
    op.drop_index(op.f('executions_id_idx'), table_name='executions')
    op.drop_index(op.f('executions_created_at_idx'), table_name='executions')
    op.create_index(
        'ix_events_timestamp',
        'events',
        ['timestamp'],
        unique=False
    )
    op.drop_index(op.f('events_timestamp_idx'), table_name='events')
    op.drop_index(op.f('events_id_idx'), table_name='events')
    op.drop_index(op.f('deployments_id_idx'), table_name='deployments')
    op.drop_index(op.f('deployments_created_at_idx'), table_name='deployments')
    op.drop_index(
        op.f('deployment_updates_id_idx'),
        table_name='deployment_updates'
    )
    op.drop_index(
        op.f('deployment_updates_created_at_idx'),
        table_name='deployment_updates'
    )
    op.drop_index(
        op.f('deployment_update_steps_id_idx'),
        table_name='deployment_update_steps'
    )
    op.drop_index(
        op.f('deployment_modifications_id_idx'),
        table_name='deployment_modifications'
    )
    op.drop_index(
        op.f('deployment_modifications_ended_at_idx'),
        table_name='deployment_modifications'
    )
    op.drop_index(
        op.f('deployment_modifications_created_at_idx'),
        table_name='deployment_modifications'
    )
    op.drop_index(op.f('blueprints_id_idx'), table_name='blueprints')
    op.drop_index(op.f('blueprints_created_at_idx'), table_name='blueprints')
    # ### end Alembic commands ###
