"""empty message

Revision ID: a2609b747f8a
Revises: 272e61bf5f4a
Create Date: 2022-05-19 13:35:45.554132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2609b747f8a'
down_revision = '272e61bf5f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_token_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
