apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      requests:
        cpu: 0.3Gi
        memory: 0.5Gi
      limits:
        cpu: 0.3Gi
        memory: 0.5Gi
  - name: python
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 2Gi
        memory: 4Gi
      limits:
        cpu: 2Gi
        memory: 4Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rabbitmq
    image: rabbitmq:3.7.7
    resources:
      requests:
        cpu: 0.3Gi
        memory: 0.5Gi
      limits:
        cpu: 0.3Gi
        memory: 0.5Gi
  - name: postgres
    image: circleci/postgres:9.5-alpine
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: cloudify_db
    resources:
      requests:
        cpu: 0.3Gi
        memory: 0.5Gi
      limits:
        cpu: 0.3Gi
        memory: 0.5Gi
  nodeSelector:
    instance-type: spot-xlarge
