apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.11.2-2
    resources:
      limits:
        cpu: 0.5
        memory: 256Mi
  - name: python
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.11
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 2
        memory: 4Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: postgres
    image: postgres:14.4-alpine
    ports:
      - containerPort: 5432
    args:
      - "-c"
      - "max_connections=800"
      # the following settings make the database very fast FOR TESTS, but will
      # remove all resistance to crashes and power losses.
      # NEVER USE IN PRODUCTION!!! SERIOUSLY! YOU WILL LOSE ALL YOUR DATA!
      - "-c"
      - "fsync=off"  # never use in production
      - "-c"
      - "synchronous_commit=off"  # never use in production
      - "-c"
      - "full_page_writes=off"  # never use in production
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: cloudify_test_db
    resources:
      limits:
        memory: 1Gi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
