apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: python
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 2.4
        memory: 4Gi
      limits:
        cpu: 2.4
        memory: 4Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: postgres
    image: circleci/postgres:9.5-alpine
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: cloudify_db
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
