apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: python
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
      limits:
        cpu: 1.5
        memory: 3Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: rpmbuild/centos7
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 0.5
        memory: 1Gi
      limits:
        cpu: 0.5
        memory: 1Gi
    securityContext:
      runAsUser: 0
      privileged: true
  - name: python-old
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
  - name: rabbitmq
    image: rabbitmq:3.7.7
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: postgres
    image: circleci/postgres:9.5-alpine
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: cloudify_db
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  nodeSelector:
    instance-type: spot-xlarge
