apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.5
        memory: 256Mi
  - name: python
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.6
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        memory: 5Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: postgres
    image: circleci/postgres:9.5-alpine
    ports:
      - containerPort: 5432
    args:
      - "-c"
      - "max_connections=800"
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: cloudify_test_db
    resources:
      limits:
        memory: 1Gi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
