apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: rpmbuild
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-rpmbuild
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 1
        memory: 2Gi
    securityContext:
      runAsUser: 0
      privileged: true
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  nodeSelector:
    instance-type: spot
