imports:
    - "cloudify.types"
    - "testmockoperations.yaml"

blueprint:
    name: "single_node"
    topology:
        -   name: "single_node"
            type: "mock_type"


types:
    mock_type:
        derived_from: cloudify.types.base
        interfaces:
            mock_interface:
                - mock_operation:
                      mapping: 'testmockoperations.tasks.mock_operation'
                      properties:
                          mockprop: 'mockpropvalue'
                          mockprop2: 'mockpropvalue2'
                - make_reachable: testmockoperations.tasks.make_reachable
                - make_unreachable: testmockoperations.tasks.make_unreachable
        workflows:
            create:
                radial: |
                    define mock_create
                        execute_operation operation: 'make_reachable'
            start:
                radial: |
                    define mock_start
                        execute_operation operation: 'mock_operation'
            delete:
                radial: |
                    define mock_delete
                        execute_operation operation: 'make_unreachable'
