imports:
  - "cloudify.types"
  - "cloudmock.yaml"
  - "testmockoperations.yaml"

blueprint:
  name: "multi_instance"
  nodes:
    - name: "host"
      type: "cloudify.types.host"
      interfaces:
        cloudify.interfaces.lifecycle:
          - create: cloudmock.tasks.provision
          - start: cloudmock.tasks.start
      instances:
        deploy: 2
    - name: "app_module"
      type: "cloudify.types.app_module"
      interfaces:
          mock_interface:
              - "touch": testmockoperations.tasks.touch
              - "make_reachable": testmockoperations.tasks.make_reachable
              - "make_unreachable": testmockoperations.tasks.make_unreachable
              - "set_property": testmockoperations.tasks.set_property
      relationships:
        - type: "cloudify.relationships.contained_in"
          target: "host"
      workflows:
        create:
          radial: |
            define app_module_init
              execute_operation operation: 'make_reachable'
