imports:
    - "cloudify.types"
    - "cloudmock.yaml"
    - "connectionconfigurermock.yaml"
    - "testmockoperations.yaml"

blueprint:
    name: "simple_web_server"
    nodes:
        -   name: "host"
            type: "test_host_type"
            interfaces:
                cloudify.interfaces.host:
                    - get_state: cloudmock.tasks.get_state
                cloudify.interfaces.lifecycle:
                    - create: cloudmock.tasks.provision
                    - start: cloudmock.tasks.start
            properties:
                target_property_key: 'target_property_value'
        -   name: "mock_node_that_connects_to_host"
            type: "test_app_module_type"
            properties:
                source_property_key: 'source_property_value'
            interfaces:
                cloudify.interfaces.lifecycle:
                    - start: testmockoperations.tasks.make_reachable
                mock_interface:
                    - "touch": testmockoperations.tasks.touch
                    - "make_reachable": testmockoperations.tasks.make_reachable
                    - "make_unreachable": testmockoperations.tasks.make_unreachable
                    - "set_property": testmockoperations.tasks.set_property
            relationships:
                -   type: "cloudify.relationships.connected_to"
                    target: "host"
                    source_interfaces:
                        cloudify.interfaces.relationship_lifecycle:
                            - postconfigure: connection_configurer_mock.tasks.configure_connection

types:
    test_host_type:
        derived_from: "cloudify.types.host"
        properties:
            - target_property_key
    test_app_module_type:
        derived_from: "cloudify.types.app_module"
        properties:
            - source_property_key
