/*******************************************************************************
 * Copyright (c) 2013 GigaSpaces Technologies Ltd. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/

import org.cloudifysource.cosmo.agent.messages.ProbeAgentMessage
import org.cloudifysource.cosmo.statecache.messages.StateChangedMessage
import org.cloudifysource.cosmo.monitor.Agent

declare Agent
@role(event)
end

declare ProbeAgentMessage
@role(event)
end

rule "Inject Failure Rule"
    dialect "mvel"
when
    Agent( $agentId : agentId)
    not ProbeAgentMessage( agentId == $agentId)
then
    message = new ProbeAgentMessage()
    message.agentId = $agentId
    insert(message)
    insert(Class.forName("DoesNotExist---FailureInjectionClass").newInstance())
end
