########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
MANAGER_BRANCH = ENV['tag']
PACKAGER_BRANCH = ENV['PACKAGER_BRANCH']
REPO = ENV['REPO']
GITHUB_USERNAME = ENV['GITHUB_USERNAME']
GITHUB_PASSWORD = ENV['GITHUB_PASSWORD']

Vagrant.configure('2') do |config|
  config.vm.define "install_rpm" do |rpm|
    rpm.vm.box = "dummy"
    rpm.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    rpm.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-0726a974"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant install RPM build" }
      aws.security_groups = "vagrant_linux_build"
    end
    rpm.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID} #{AWS_ACCESS_KEY} #{REPO} #{GITHUB_USERNAME} #{GITHUB_PASSWORD}"
      s.privileged = false
    end
  end
end
