########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
AWS_ACCESS_KEY_ID_UPLOAD_TEMP = ENV['AWS_ACCESS_KEY_ID_UPLOAD_TEMP']
AWS_ACCESS_KEY_UPLOAD_TEMP = ENV['AWS_ACCESS_KEY_UPLOAD_TEMP']

CENTOS7_OFFICIAL_BOX_URL = 'http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7.box'

Vagrant.configure('2') do |config|
  config.vm.define "elasticsearch_curator" do |curator|
    #dummy box, will be overriden
    curator.vm.box = "dummy"
    curator.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    curator.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-fd69068a"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant curator build" }
      aws.security_groups = "vagrant_linux_build"
    end
    curator.vm.provision "shell" do |s|
      s.path = "elasticsearch_curator/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

  config.vm.define "elasticsearch_curator_redhat7" do |curator|
    #dummy box, will be overriden
    curator.vm.box = "dummy"
    curator.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    curator.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-25158352"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      aws.user_data = "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant es curator redhat7 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    curator.vm.provision "shell" do |s|
      s.path = "elasticsearch_curator/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

  config.vm.define "restservice" do |rest|
    #dummy box, will be overriden
    rest.vm.box = "dummy"
    rest.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    rest.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-fd69068a"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant rest 7.0 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    rest.vm.provision "shell" do |s|
      s.path = "restservice/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

  config.vm.define "restservice_redhat7" do |rest|
    #dummy box, will be overriden
    rest.vm.box = "dummy"
    rest.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    rest.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-25158352"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      aws.user_data = "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant rest redhat7 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    rest.vm.provision "shell" do |s|
      s.path = "restservice/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

  config.vm.define "mgmtworker" do |mgmtworker|
    #dummy box, will be overriden
    mgmtworker.vm.box = "dummy"
    mgmtworker.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    mgmtworker.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-fd69068a"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant mgmtworker 7.0 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    mgmtworker.vm.provision "shell" do |s|
      s.path = "mgmtworker/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

  config.vm.define "mgmtworker_redhat7" do |mgmtworker|
    #dummy box, will be overriden
    mgmtworker.vm.box = "dummy"
    mgmtworker.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    mgmtworker.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY
      aws.ami = "ami-25158352"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"
      aws.keypair_name = "vagrant_build"
      aws.user_data = "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"
      override.nfs.functional = false
      aws.tags = { "Name" => "vagrant mgmtworker redhat7 build" }
      aws.security_groups = "vagrant_linux_build"
    end
    mgmtworker.vm.provision "shell" do |s|
      s.path = "mgmtworker/provision.sh"
      s.args = "#{AWS_ACCESS_KEY_ID_UPLOAD_TEMP} #{AWS_ACCESS_KEY_UPLOAD_TEMP}"
      s.privileged = false
    end
  end

end
